### PR TITLE
Multistage image build for powerflex metrics

### PR DESCRIPTION
**Pull request by panigs7**
# Description
Implementation of multistage docker build for Powerflex metrics

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/1098 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have inspected the Grafana dashboards to verify the data is displayed properly
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have maintained backward compatibility

# How Has This Been Tested?
image
image

### CODE REVIEW

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Review by nitesh3108 — APPROVED** [review]

**Comment by nitesh3108** [comment]
e2e pass

**Comment by rajendraindukuri** [comment]
e2e pass

**Comment by rajendraindukuri** [comment]
skip e2e

**Review by donatwork — APPROVED** [review]

**Comment by donatwork** [comment]
e2e pass

**Pull request merged**
