### PR TITLE
Updated goscaleio client

### PR DESCRIPTION
**Pull request by tdawe**
# Description
Updated goscaleio client

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/117  |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [x] Executed unit tests

### CODE REVIEW

**Comment by tdawe** [comment]
run e2e

**Comment by tdawe** [comment]
run e2e test

**Comment by tdawe** [comment]
run e2e test

**Review by AronAtDell — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Comment by tdawe** [comment]
run e2e test

**Pull request merged**
