### PR TITLE
Go 117 dependency update

### PR DESCRIPTION
**Pull request by LJ-Software**
# Description
Updated the go version of this module to 1.17 and updated the version of all of the module dependencies to latest.

All of the otel modules were updated to newer versions bringing with it many changes in the code to accommodate. Most of the changes are method & attribute name changes in the otel libraries.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| N/A |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?

- [x] End to End integration test with Observability
```
--- PASS: Test_Metrics (58.55s)
    --- PASS: Test_Metrics/Powerflex_Volume_Metrics (14.19s)
    --- PASS: Test_Metrics/Powerflex_Storage_Pool (14.17s)
    --- PASS: Test_Metrics/Powerflex_ExportNode_Metrics (30.18s)
PASS
ok      karavi-testing/karavi-metrics/metrics-test      58.584s
```

### CODE REVIEW

**Review by hoppea2 — COMMENTED** [review]
go unit test step failed:
go: golang.org/x/net@v0.0.0-2022012[7](https://github.com/dell/karavi-metrics-powerflex/runs/5048292551?check_suite_focus=true#step:4:7)200216-cd36cc0744dd requires
	golang.org/x/sys@v0.0.0-20211216021012-1d35b9e2eb4e: missing go.sum entry; to add it:
	go mod download golang.org/x/sys

**Comment by alikdell** [comment]
actions.yaml has following:
  
  steps:
      - name: Set up Go 1.14+
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14

**Comment by LJ-Software** [comment]
run e2e test

**Comment by LJ-Software** [comment]
run e2e test pass

**Comment by alikdell** [comment]
e2e test pass

**Comment by alikdell** [comment]
e2e pass

**Review by shaynafinocchiaro — APPROVED** [review]

**Review by hoppea2 — APPROVED** [review]

**Pull request merged**
