### PR TITLE
BUGXIX-63 - do not fail when PVs without CSI exists

### PR DESCRIPTION
**Pull request by TomasKohout**
# Description

A few sentences describing the overall goals of the pull request's commits.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
|   [issue-63](https://github.com/dell/karavi-observability/issues/63)       |

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have run 'make check' to ensure my code does not have any formatting, vetting, linting, or security issues
- [x] I have run 'make test' to ensure new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degrade
- [x] I have maintained at least 90% code coverage
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- tested on cluster with PVs without CSI field

### CODE REVIEW

**Comment by ioeicicdsvc** [comment]
Can one of the admins verify this patch?

**Review by tdawe — DISMISSED** [review]

**Comment by gallacher** [comment]
run e2e test

**Review by alikdell — APPROVED** [review]

**Comment by TomasKohout** [comment]
I've added test for verification. :slightly_smiling_face:

**Comment by gallacher** [comment]
run e2e test

**Comment by hoppea2** [comment]
merged in dependency update from main to fix issue in security scan

**Review by hoppea2 — APPROVED** [review]

**Review by gallacher — APPROVED** [review]

**Comment by tdawe** [comment]
run e2e test

**Comment by tdawe** [comment]
e2e pass

**Comment by tdawe** [comment]
e2e was executed manually and passed successfully

**Comment by gallacher** [comment]
@TomasKohout, thank you very much for your contribution!

**Comment by TomasKohout** [comment]
It was my pleasure! 🙌

**Pull request merged**
