### PR TITLE
go version bump-up

### PR DESCRIPTION
**Pull request by nitesh3108**
Updating go version to latest available i.e. => 1.22

### CODE REVIEW

**Review by AronAtDell — APPROVED** [review]

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Review by KerryKovacevic — APPROVED** [review]

**Review by shaynafinocchiaro — APPROVED** [review]

**Comment by atye** [comment]
run e2e test

**Review by donatwork — APPROVED** [review]
skip e2e test

**Review by shefali-malhotra — APPROVED** [review]
LGTM

**Comment by donatwork** [comment]
e2e pass

**Pull request merged**
