### PR TITLE
Remove Karavi observability deployment documentation from Karavi-metrics-powerflex repository

### PR DESCRIPTION
**Pull request by sharmilarama**
# Description

This PR removes duplicate documentation for Karavi observability deployment.

# Issues

List the issues impacted by this PR:

| Issue ID |
| -------- |
| https://github.com/dell/karavi-observability/issues/1  |

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have run 'make check' to ensure my code does not have any formatting, vetting, linting, or security issues
- [ ] I have run 'make test' to ensure new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degrade
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

N/A

### CODE REVIEW

**Review by alikdell — APPROVED** [review]

**Review by hoppea2 — APPROVED** [review]

**Review by gallacher — APPROVED** [review]

**Comment by gallacher** [comment]
e2e passed

**Comment by gallacher** [comment]
e2e pass

**Comment by gallacher** [comment]
e2e passed

**Comment by gallacher** [comment]
e2e pass

**Comment by tdawe** [comment]
e2e pass

**Review by gallacher — APPROVED** [review]

**Pull request merged**
