### PR TITLE
upgrade OTEL version to v1.7.0.

### PR DESCRIPTION
**Pull request by taohe1012**
# Description
upgrade OTEL version to v1.7.0:
 - upgrade otel version to 1.7.0, and its subpackages to v0.30.0;
 - use Async UpDownCounter instead of Sync UpDownCounter;

Note: we upgrade the OpenTelemetry to v1.7.0, and its subpackages to v0.30.0, to use Async UpDownCounter instead of Sync UpDownCounter.

According official reference, [UpDownCounter](https://opentelemetry.io/docs/reference/specification/metrics/api/#updowncounter) :
For fetching the snapshot of the “current value” is straightforward, use Asynchronous UpDownCounter instead, not Synchronous UpDownCounter.
# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/356 |

# Checklist:

- [x] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [x] I have verified that new and existing unit tests pass locally with my changes
- [x] I have not allowed coverage numbers to degenerate
- [x] I have maintained at least 90% code coverage
- [x] I have inspected the Grafana dashboards to verify the data is displayed properly
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have maintained backward compatibility

# How Has This Been Tested?
- [x] Test A: UT tests
ut_result

- [x] Test B: Grafana Volume IO Metrics: checked it value is consistent with PFlex Mgmt UI's volume value
PFlex Mgmt UI:
pflexGUI_volume
Grafana:
grafana_volume2

- [x] Test C: Grafana storage System I/O Metrics by Node: checked it value is consistent with PFlex Mgmt UI's sdc value
PFlex Mgmt UI:
pflexGUI_sdc_node
Grafana:
grafana_node2

- [x] Test D: Grafana Storage Pool and Storage Class Capacity: 
checked it value: 
1) Free Capacity and Provisioned is consistent with PFlex Mgmt UI's storage pool value
2) Total Capacity and Used Capacity are actually TotalLogicalCapacity and LogicalCapacityInUse, they are is consistent with code logic: Total Capacity = usedCapacity + freeCapacity
PFlex Mgmt UI:
pflexGUI_sp_cap

Grafana:
grafana_storagepool_total2

# Manual inspection of the GUI
I have verified that the dashboards show the data properly while generating I/O and storage resources

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
hello everyone, do I need to add some setup to run Image Scanner, or need permission? thanks
image

**Comment by taohe1012** [comment]
e2e passed, all metric tests passed
image

**Review by forrestxia — APPROVED** [review]

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
run e2e test

**Comment by taohe1012** [comment]
run e2e test

**Review by forrestxia — APPROVED** [review]

**Comment by alikdell** [comment]
e2e pass

**Review by alikdell — APPROVED** [review]

**Review by baoy1 — APPROVED** [review]

**Pull request merged**
